name: Deploy to Hestia

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup SSH
      env:
        SSH_KEY: ${{ secrets.DEPLOY_KEY }}
        SSH_HOST: ${{ secrets.SERVER_HOST }}
        SSH_USER: ${{ secrets.SERVER_USER }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

    - name: Rsync to server
      run: |
        rsync -avz --delete \
          --exclude='.git*' --exclude='tests' \
          ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/web/lp.easyrent.world/public_html/
